# Generated by Django 5.0.5 on 2024-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CemalCemil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('pesanan', models.TextField()),
                ('total', models.TextField()),
                ('uang_masuk', models.TextField()),
                ('kembalian', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_meja', models.CharField(max_length=100)),
                ('pesanan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pesanan', models.CharField(max_length=100)),
                ('pembelian', models.TextField()),
                ('jumlah', models.TextField()),
                ('total', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
