# Generated by Django 5.0.5 on 2024-05-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CemalCemil', '0002_kasir_meja_pesanan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesanan',
            old_name='pembelian',
            new_name='meja',
        ),
    ]
