# Generated by Django 5.0.5 on 2024-05-10 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CemalCemil', '0004_remove_pelanggan_pesanan_alter_pelanggan_nama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kasir',
            name='pesanan',
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='Pesanan',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='kasir',
            name='Pesanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kasir', to='CemalCemil.pesanan'),
            preserve_default=False,
        ),
    ]
