# Generated by Django 5.0.5 on 2024-07-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CemalCemil', '0005_remove_kasir_pesanan_remove_pelanggan_pesanan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='meja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pelanggan', to='CemalCemil.meja'),
            preserve_default=False,
        ),
    ]
